version: '3'
services:
  backend-api:
    build: assignment/.
    ports:
      - "5000:5000"
    networks:
      - my-network  
  application:
    build: frontend-app/.
    ports:
      - "80:80"
    networks:
      - my-network  
networks:
  my-network: